version: '3'
services:
  ev3rt:
    image: mikoto2000/hakoniwa-ev3rt-devkit:latest
    working_dir: /ev3rt-athrill-v850e2m/sdk/workspace
    restart: "no"
    command: ["sleep", "infinity"]
    ports:
      - "54002:54002/udp"
    volumes:
      - "../:/ev3rt-athrill-v850e2m/sdk/workspace/app"

